spring:
  config:
    activate:
      on-profile: dev

  web:
    resources:
      static-locations: classpath:/static/, file:./${UPLOAD_DIR:uploads}/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080

app:
  upload:
    dir: ${UPLOAD_DIR:uploads}
    base-url: ${UPLOAD_BASE_URL:http://localhost:8080/uploads}

custom:
  jwt:
    secretKey: ${JWT_SECRET}
